# config.yaml
host:
  name: "chuk-mcp-s3-bucket-manager"
  log_level: "INFO"

server:
  type: "stdio"  # or "websocket" if you prefer network-based communication

mcp_servers:
  s3_bucket_manager:
    enabled: true
    location: "."
    tools:
      enabled: true
      module: "chuk_mcp_s3_bucket_manager.tools"
